### ISSUE TITLE
UI: New_node menu not scrollable

### ISSUE THREAD

**Issue by kchapelier** [szymonkaliski/SDF-UI#1]
The new_node menu (displayed when double-clicking on the editor) is not scrollable.

On relatively small screen, like my 1440x900 laptop, this means the upper part of the menu is not accessible.

Screenshot: 

<img width="1062" alt="default" src="https://cloud.githubusercontent.com/assets/5741699/22405543/baadcc8a-e644-11e6-8920-1c55c5f835e2.png">

**Comment by szymonkaliski** [comment]
fixed in https://github.com/szymonkaliski/SDF-UI/commit/b444bad67ad46298eec25241a73d2d2a3fd8255c
