### ISSUE TITLE
Objects are not rendered in Chrome on Linux

### ISSUE THREAD

**Issue by pwittchen** [szymonkaliski/SDF-UI#2]
Hi Szymon,

Really cool project!

Unfortunately, it doesn't work in Chrome on Linux (objects are not rendered). I'm attaching a screenshot.
My configuration: Ubuntu 16.04.1 LTS 64-bit, Chrome v. 53.0.2785.116 (64-bit).
It's worth mentioning that it works fine on the same system on Firefox 51.0.1 (64 bit).

**Edit**:

I think, it may be an issue related to gl-react, because its samples also doesn't work on Chrome in my setup, but works on Firefox.

![screenshot](https://cloud.githubusercontent.com/assets/695319/22407351/2f5c1062-e665-11e6-8040-737e0c6b4e68.png)

Regards,
Piotr

**Comment by szymonkaliski** [comment]
Huh, strange, any errors in the console?

Edit: also your chrome looks outdated, could you update and try again?

**Comment by pwittchen** [comment]
I got only something like that in the console in Chrome Dev Tools:

```
index.js:87 No handler for action @@redux/INIT
```

It's marked as a warning.

**Comment by szymonkaliski** [comment]
That's not a problem really. What about that outdated chrome?

**Comment by pwittchen** [comment]
Maybe it's an issue with older version of the browser. I've noticed that I have Chromium browser v. 55.0.2883.87 Built on Ubuntu, running on Ubuntu 16.04 (64-bit) and in this browser, app works fine. I think we can close that issue :).
