### ISSUE TITLE
Addition op should have parantheses

### ISSUE THREAD

**Issue by t1tan** [szymonkaliski/SDF-UI#4]
Addition simply outputs a + b. It should output (a + b) or even better ((a) + (b)). 
As of right now (sin(t/400) + 1) / 2 is impossible because of this (the output is "sin(t/400) + 1 / 2" which is not the same thing)

**Comment by szymonkaliski** [comment]
Nice catch, thanks! Would you like to submit PR? Would be simple change in math-add.js :) otherwise I'll do it tomorrow. Cheers!

**Comment by szymonkaliski** [comment]
Ok, fixed in https://github.com/szymonkaliski/SDF-UI/commit/33d585637ff091bcfa0a82172d7e6765f2832197

**Comment by t1tan** [comment]
Thank you, that was quick. Tested it. It works.
