### ISSUE TITLE
Firefox OSX delete goes back a step in page history

### ISSUE THREAD

**Issue by MacroMachines** [szymonkaliski/SDF-UI#7]
Firefox OSX seems to work the best so far out of the browsers I tried, the only issue being that delete/backspace both deletes the selected node and issues a hotkey to the firefox browser to go back to the previous page in history.  

Overall the solution to the backspace issue could be an additional method of removing a connection or node, such as:
 a context menu for cut/copy/paste/delete invoked from a command click aka right click
 an additional / alternate key for delete, possibly "d"?

**Comment by MacroMachines** [comment]
Open a new Firefox window.
    Enter about:config into the location bar. Press Enter. ...
    Enter browser.backspace into the filter. ...
    Contrl-click the 'Browser.backspace_action' Value column, 
and choose Modify from the pop-up menu, 
then enter a new value of 2.
    Press OK.

**Comment by szymonkaliski** [comment]
Great, closing for now then. Feel free to reopen if needed!
